name: flyingdarts_frontend_flutter_features_speech
description: "A package containg the speech feature."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  get_it: ^7.6.4

  flyingdarts_frontend_flutter_shared_ui:
  flyingdarts_frontend_flutter_features_language:
  flyingdarts_frontend_flutter_shared_configuration:
  flyingdarts_frontend_flutter_shared_configuration_preferences:
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  equatable: ^2.0.5
  speech_to_text:
    git:
      url: https://github.com/flyingdarts/speech_to_text.git
      path: speech_to_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.6
  widgetbook_generator: ^3.13.0

flutter:
