name: flyingdarts_frontend_flutter_core
description: "A flutter package used to configure dependencies and modules"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.0.15
  get_it: ^7.6.0
  injectable: ^2.3.0

  flyingdarts_frontend_flutter_shared_websocket:
  flyingdarts_frontend_flutter_shared_configuration:
  flyingdarts_frontend_flutter_shared_configuration_preferences:
  flyingdarts_frontend_flutter_shared_configuration_secrets:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  injectable_generator: ^2.3.0
  build_runner: ^2.4.6

flutter:
