name: flyingdarts_frontend_flutter_features_dartboard
description: "A package containing the dartboard feature"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.8.0

  flyingdarts_frontend_flutter_shared_ui:

  flyingdarts_frontend_flutter_shared_internationalization:

  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.6
  widgetbook_generator: ^3.13.0
flutter:
