#!/bin/bash

# 🧹 Beachball Cleanup Script for Flyingdarts Monorepo
# This script removes all beachball-generated files and resets package.json versions to 0.0.1

set -e # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Function to check if we're in the right directory
check_workspace() {
    if [[ ! -f "package.json" ]] || [[ ! -f "beachball.config.js" ]]; then
        print_error "This script must be run from the root of the flyingdarts-turbo workspace!"
        print_error "Expected files: package.json and beachball.config.js"
        exit 1
    fi
}

# Function to confirm user wants to proceed
confirm_cleanup() {
    print_warning "🚨 This script will perform the following actions:"
    echo "   1. Remove ALL CHANGELOG.json and CHANGELOG.md files generated by beachball"
    echo "   2. Reset ALL package.json version fields to '0.0.1'"
    echo ""
    print_warning "⚠️  This action cannot be undone!"
    echo ""

    read -p "Are you sure you want to proceed? (yes/no): " -r
    echo

    if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        print_status "Cleanup cancelled by user."
        exit 0
    fi

    print_status "Proceeding with cleanup..."
}

# Function to remove CHANGELOG files
remove_changelog_files() {
    print_status "Removing beachball-generated CHANGELOG files..."

    local changelog_count=0

    # Find and remove all CHANGELOG.json and CHANGELOG.md files (excluding node_modules)
    find . \( -name "CHANGELOG.json" -o -name "CHANGELOG.md" -o -name "changelog.md" \) -type f -not -path "./node_modules/*" 2>/dev/null | while IFS= read -r file; do
        if [[ -f "$file" ]]; then
            rm "$file"
            changelog_count=$((changelog_count + 1))
            print_success "Removed: $file"
        fi
    done

    if [[ $changelog_count -eq 0 ]]; then
        print_status "No CHANGELOG files found to remove."
    else
        print_success "Removed $changelog_count CHANGELOG files."
    fi
}

# Function to reset package.json versions
reset_package_versions() {
    print_status "Resetting package.json versions to '0.0.1'..."

    local package_count=0

    # Find all package.json files (excluding node_modules)
    find . -name "package.json" -type f -not -path "./node_modules/*" 2>/dev/null | while IFS= read -r file; do
        if [[ -f "$file" ]]; then
            # Use jq to update the version field if it exists
            if command -v jq &>/dev/null; then
                # Check if the file has a version field
                if jq -e '.version' "$file" >/dev/null 2>&1; then
                    # Update version to 0.0.1
                    jq '.version = "0.0.1"' "$file" >"${file}.tmp" && mv "${file}.tmp" "$file"
                    package_count=$((package_count + 1))
                    print_success "Updated version in: $file"
                fi
            else
                # Fallback to sed if jq is not available
                if grep -q '"version"' "$file"; then
                    # This is a simple sed replacement - may need adjustment for complex JSON
                    sed -i.bak 's/"version": "[^"]*"/"version": "0.0.1"/g' "$file"
                    rm "${file}.bak" 2>/dev/null || true
                    package_count=$((package_count + 1))
                    print_success "Updated version in: $file"
                fi
            fi
        fi
    done

    if [[ $package_count -eq 0 ]]; then
        print_warning "No package.json files found or updated."
    else
        print_success "Updated version in $package_count package.json files."
    fi
}

# Function to display summary
display_summary() {
    echo ""
    print_success "🎉 Beachball cleanup completed successfully!"
    echo ""
    print_status "Summary of actions performed:"
    echo "   ✅ Removed all CHANGELOG.json and CHANGELOG.md files"
    echo "   ✅ Reset all package.json versions to '0.0.1'"
    echo ""
    print_status "Next steps:"
    echo "   1. Review the changes with 'git status'"
    echo "   2. Commit the changes if you're satisfied"
    echo "   3. Run 'npm run beachball:check' to verify clean state"
    echo "   4. Start fresh with beachball when ready"
    echo ""
}

# Main execution
main() {
    echo "🧹 Beachball Cleanup Script for Flyingdarts Monorepo"
    echo "=================================================="
    echo ""

    # Check if we're in the right directory
    check_workspace

    # Confirm user wants to proceed
    confirm_cleanup

    # Perform cleanup operations
    remove_changelog_files
    reset_package_versions

    # Display summary
    display_summary
}

# Run the main function
main "$@"
