global using Amazon.CDK;
global using Amazon.CDK.AWS.APIGateway;
global using Amazon.CDK.AWS.Apigatewayv2.Alpha;
global using Amazon.CDK.AWS.Apigatewayv2.Authorizers.Alpha;
global using Amazon.CDK.AWS.Apigatewayv2.Integrations.Alpha;
global using Amazon.CDK.AWS.CertificateManager;
global using Amazon.CDK.AWS.CloudFront;
global using Amazon.CDK.AWS.CloudFront.Origins;
global using Amazon.CDK.AWS.DynamoDB;
global using Amazon.CDK.AWS.IAM;
global using Amazon.CDK.AWS.Lambda;
global using Amazon.CDK.AWS.Route53;
global using Amazon.CDK.AWS.S3;
global using Amazon.CDK.AWS.SSM;
global using Amazon.JSII.Runtime.Deputy;
global using Constructs;
global using AmazonAspect = Amazon.CDK.Aspects;
global using Attribute = Amazon.CDK.AWS.DynamoDB.Attribute;
global using Construct = Constructs.Construct;
global using Function = Amazon.CDK.AWS.Lambda.Function;
global using FunctionProps = Amazon.CDK.AWS.Lambda.FunctionProps;
global using Stage = Amazon.CDK.AWS.APIGateway.Stage;
global using StageProps = Amazon.CDK.AWS.APIGateway.StageProps;
